# Generated by Django 5.2.4 on 2025-10-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'email']},
        ),
    ]
