# Generated by Django 5.2.4 on 2025-10-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat_api.channel",
            ),
        ),
    ]
