# Generated by Django 5.2.4 on 2025-10-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_message_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
