# Generated by Django 5.2.4 on 2025-10-30 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0004_message_parent_message_dmconversation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(
                fields=["user", "channel"], name="chat_api_ch_user_id_98a808_idx"
            ),
        ),
    ]
