# Generated by Django 5.2.4 on 2025-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
