# Generated by Django 5.2.4 on 2025-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
