# Generated by Django 5.2.4 on 2025-10-21 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile_api", "0002_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_login",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                default="Write something about yourself...", max_length=500
            ),
        ),
    ]
